---
- name: Ensure Qpid Dispatch packages are installed
  yum:
    name: "{{ item }}"
    state: latest
    enablerepo: epel
  with_items: "{{ dispatch_packages }}"
  notify:
    - qdrouterd is enabled
    - qdrouterd is started
